import api from './api';

export const getTeacherDashboard = () => api.get('/teachers/dashboard');
export const getTeacherProfile = () => api.get('/teachers/profile');
export const getTeacherStudents = (params) => api.get('/teachers/students', { params });
export const getTeacherTimetable = () => api.get('/teachers/timetable');
export const getTeacherLeaves = (params) => api.get('/teachers/leaves', { params });
export const createTeacherLeave = (data) => api.post('/teachers/leaves', data);
export const getMyClasses = () => api.get('/teachers/profile');
export const getStudents = (params) => api.get('/students', { params });
export const getStudentById = (id) => api.get(`/students/${id}`);
export const markAttendance = (data) => api.post('/attendance', data);
export const getAttendance = (params) => api.get('/attendance', { params });
export const getStudentAttendance = (studentId, params) => api.get(`/attendance/student/${studentId}`, { params });
export const getHomework = (params) => api.get('/homework', { params });
export const createHomework = (data) => api.post('/homework', data);
export const updateHomework = (id, data) => api.put(`/homework/${id}`, data);
export const deleteHomework = (id) => api.delete(`/homework/${id}`);
export const getAssignments = (params) => api.get('/assignments', { params });
export const createAssignment = (data) => api.post('/assignments', data);
export const updateAssignment = (id, data) => api.put(`/assignments/${id}`, data);
export const deleteAssignment = (id) => api.delete(`/assignments/${id}`);
export const getResults = (params) => api.get('/results', { params });
export const createResult = (data) => api.post('/results', data);
export const updateResult = (id, data) => api.put(`/results/${id}`, data);
export const bulkCreateResults = (data) => api.post('/results/bulk', data);
export const getClasses = (params) => api.get('/classes', { params });
export const getSections = (params) => api.get('/sections', { params });
export const getSubjects = (params) => api.get('/subjects', { params });
export const getExams = (params) => api.get('/exams', { params });
export const getNotices = () => api.get('/notices');
export const getNotifications = (params) => api.get('/notifications', { params });
export const markNotificationRead = (id) => api.put(`/notifications/${id}/read`);
export const updatePassword = (data) => api.put('/auth/update-password', data);
export const updateProfile = (data) => api.put('/auth/update-profile', data);
export const getEvents = () => api.get('/events');
export const getStudyMaterials = (params) => api.get('/materials', { params });
export const createStudyMaterial = (data) => api.post('/materials', data);
export const updateStudyMaterial = (id, data) => api.put(`/materials/${id}`, data);
export const deleteStudyMaterial = (id) => api.delete(`/materials/${id}`);
export const getUploadUrl = () => '/uploads';
