import { HiOutlineAcademicCap, HiOutlineBeaker, HiOutlineBookOpen, HiOutlineBuildingOffice2, HiOutlineComputerDesktop, HiOutlineGlobeAlt, HiOutlineHeart, HiOutlineMusicalNote, HiOutlineSparkles, HiOutlineTrophy, HiOutlineTruck } from 'react-icons/hi2';

const facilitiesData = [
  {
    id: 1,
    title: 'Smart Classrooms',
    category: 'Academic',
    description: 'All classrooms are equipped with interactive smart boards, projectors, and modern audio-visual aids to enhance the learning experience.',
    longDescription: 'Our 50+ smart classrooms feature 86-inch interactive flat panels, document cameras, and sound systems. Teachers use digital content platforms to deliver engaging lessons. Classrooms are designed for collaborative learning with flexible seating arrangements.',
    image: 'https://plus.unsplash.com/premium_photo-1764691435961-ecb3a0a5d311?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTd8fFNtYXJ0JTIwQ2xhc3Nyb29tc3xlbnwwfHwwfHx8MA%3D%3D',
    icon: <HiOutlineComputerDesktop className="w-10 h-10" />,
    color: 'from-blue-500 to-blue-600',
    bgLight: 'bg-blue-50',
    textColor: 'text-blue-600',
    borderColor: 'border-blue-200',
    capacity: '40 per room',
    total: '52 classrooms',
    timing: '8:00 AM - 3:30 PM',
    incharge: 'Mr. Rajesh Kumar',
    phone: '+91 98765 43210',
    location: 'Academic Block A & B',
    features: ['Interactive Flat Panels', 'Lecture Capture', 'WiFi 6', 'Flexible Seating', 'HVAC'],
  },
  {
    id: 2,
    title: 'Computer Lab',
    category: 'Academic',
    description: 'Fully air-conditioned computer labs with 120+ latest systems, high-speed internet, and a wide range of educational software.',
    longDescription: 'Three state-of-the-art computer labs with 120 thin-client systems powered by Intel i7 processors. Labs are equipped with licensed software including Adobe Creative Suite, AutoCAD, Python IDEs, and SQL servers.',
    image: 'https://images.unsplash.com/photo-1531482615713-2afd69097998?w=600&q=80',
    icon: <HiOutlineComputerDesktop className="w-10 h-10" />,
    color: 'from-emerald-500 to-emerald-600',
    bgLight: 'bg-emerald-50',
    textColor: 'text-emerald-600',
    borderColor: 'border-emerald-200',
    capacity: '40 per lab',
    total: '3 labs (120 systems)',
    timing: '8:00 AM - 5:00 PM',
    incharge: 'Ms. Priya Sharma',
    phone: '+91 98765 43211',
    location: 'Academic Block B, Floor 2',
    features: ['i7 Systems', 'Adobe Suite', 'AutoCAD', 'High-Speed Internet', 'UPS Backup'],
  },
  {
    id: 3,
    title: 'Science Lab',
    category: 'Academic',
    description: 'Well-equipped physics, chemistry, and biology laboratories with modern apparatus and safety equipment for hands-on learning.',
    longDescription: 'Three dedicated labs for Physics, Chemistry, and Biology spread across 5000 sq ft. Each lab has individual workstations with gas, water, and electrical connections. We have digital microscopes, spectrophotometers, and a fully stocked chemical store.',
    image: 'https://images.unsplash.com/photo-1532094349884-543bc11b234d?w=600&q=80',
    icon: <HiOutlineBeaker className="w-10 h-10" />,
    color: 'from-purple-500 to-purple-600',
    bgLight: 'bg-purple-50',
    textColor: 'text-purple-600',
    borderColor: 'border-purple-200',
    capacity: '30 per lab',
    total: '3 labs',
    timing: '8:00 AM - 4:00 PM',
    incharge: 'Dr. Suresh Reddy',
    phone: '+91 98765 43212',
    location: 'Science Block, Floor 1',
    features: ['Digital Microscopes', 'Spectrophotometer', 'Safety Showers', 'Fume Hoods', 'Chemical Store'],
  },
  {
    id: 4,
    title: 'Central Library',
    category: 'Academic',
    description: 'A vast library with over 25,000 books, 100+ journals, and extensive digital resources. Quiet reading zones and group study rooms available.',
    longDescription: 'The 15,000 sq ft central library houses 25,000+ books, 120 national and international journals, and subscribes to 8 online databases including J-Gate and ProQuest. Features include a digital library section with 30 workstations, RFID-enabled checkout, a reference section, and 4 group study pods.',
    image: 'https://images.unsplash.com/photo-1568667256549-094345857637?w=600&q=80',
    icon: <HiOutlineBookOpen className="w-10 h-10" />,
    color: 'from-amber-500 to-amber-600',
    bgLight: 'bg-amber-50',
    textColor: 'text-amber-600',
    borderColor: 'border-amber-200',
    capacity: '200 readers',
    total: '25,000+ books',
    timing: '7:30 AM - 7:00 PM',
    incharge: 'Mrs. Lakshmi Nair',
    phone: '+91 98765 43213',
    location: 'Academic Block C, Floor 1-2',
    features: ['Digital Library', 'RFID System', 'Group Study Pods', 'Online Databases', 'Reference Section'],
  },
  {
    id: 5,
    title: 'Sports Complex',
    category: 'Sports',
    description: 'Extensive sports facilities including a football field, basketball court, volleyball court, indoor badminton, and a modern gymnasium.',
    longDescription: 'Our 10-acre sports complex features a FIFA-standard football pitch, 2 basketball courts, 4 volleyball courts, 6 badminton courts, a 400m synthetic athletic track, and a modern indoor gymnasium with cardio and strength training equipment.',
    image: 'https://plus.unsplash.com/premium_photo-1685088557702-a2558e0ecbb9?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8U3BvcnRzJTIwQ29tcGxleHxlbnwwfHwwfHx8MA%3D%3D',
    icon: <HiOutlineTrophy className="w-10 h-10" />,
    color: 'from-red-500 to-red-600',
    bgLight: 'bg-red-50',
    textColor: 'text-red-600',
    borderColor: 'border-red-200',
    capacity: '2000 spectators',
    total: '10 acre complex',
    timing: '6:00 AM - 6:00 PM',
    incharge: 'Coach Vikram Singh',
    phone: '+91 98765 43214',
    location: 'Sports Zone, East Campus',
    features: ['Football Pitch', 'Athletic Track', 'Basketball Courts', 'Indoor Gym', 'Swimming Pool'],
  },
  {
    id: 6,
    title: 'Transportation',
    category: 'Infrastructure',
    description: 'Safe and reliable fleet of 25 school buses covering all major routes with GPS tracking, CCTV, and trained attendants.',
    longDescription: 'Our fleet of 25 GPS-tracked buses covers 40+ routes across the city. Each bus has CCTV cameras, speed governors, first-aid kits, and a trained attendant. Parents can track bus locations in real-time through our mobile app.',
    image: 'https://images.unsplash.com/photo-1570125909232-eb263c188f7e?w=600&q=80',
    icon: <HiOutlineTruck className="w-10 h-10" />,
    color: 'from-cyan-500 to-cyan-600',
    bgLight: 'bg-cyan-50',
    textColor: 'text-cyan-600',
    borderColor: 'border-cyan-200',
    capacity: '50 per bus',
    total: '25 buses, 40 routes',
    timing: '6:30 AM - 5:00 PM',
    incharge: 'Mr. Anand Joshi',
    phone: '+91 98765 43215',
    location: 'Transport Hub, Main Gate',
    features: ['GPS Tracking', 'CCTV', 'Speed Governors', 'Trained Attendants', 'Mobile App'],
  },
  {
    id: 7,
    title: 'Medical Room',
    category: 'Health',
    description: 'A well-equipped infirmary with a full-time nurse, visiting doctor, first-aid facilities, and regular health check-up camps.',
    longDescription: 'Our 600 sq ft medical room has 4 observation beds, an examination area, and a pharmacy stocked with essential medicines. A full-time registered nurse is available during school hours, and a doctor visits twice a week.',
    image: 'https://images.unsplash.com/photo-1579154204601-01588f351e67?w=600&q=80',
    icon: <HiOutlineHeart className="w-10 h-10" />,
    color: 'from-pink-500 to-pink-600',
    bgLight: 'bg-pink-50',
    textColor: 'text-pink-600',
    borderColor: 'border-pink-200',
    capacity: '4 beds',
    total: '24/7 availability',
    timing: '7:30 AM - 4:30 PM',
    incharge: 'Nurse Sarah Thomas',
    phone: '+91 98765 43216',
    location: 'Ground Floor, Admin Block',
    features: ['Observation Beds', 'Pharmacy', 'Visiting Doctor', 'Health Camps', 'Ambulance'],
  },
  {
    id: 8,
    title: 'Cafeteria',
    category: 'Infrastructure',
    description: 'A spacious, hygienic cafeteria serving nutritious and delicious meals prepared under strict quality standards.',
    longDescription: 'Our 500-seat cafeteria serves breakfast, lunch, and snacks prepared in a modern kitchen with steam cooking, proper ventilation, and cold storage. The menu is planned by a nutritionist and changes weekly.',
    image: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=600&q=80',
    icon: <HiOutlineSparkles className="w-10 h-10" />,
    color: 'from-orange-500 to-orange-600',
    bgLight: 'bg-orange-50',
    textColor: 'text-orange-600',
    borderColor: 'border-orange-200',
    capacity: '500 seats',
    total: '3 meals daily',
    timing: '7:30 AM - 6:00 PM',
    incharge: 'Chef Mohan Das',
    phone: '+91 98765 43217',
    location: 'Student Center, Ground Floor',
    features: ['Nutritious Menu', 'Jain Counter', 'Salad Bar', 'Steam Cooking', 'AC Dining'],
  },
  {
    id: 9,
    title: 'Auditorium',
    category: 'Cultural',
    description: 'A grand 1000-seat air-conditioned auditorium with professional acoustics and stage lighting for events and assemblies.',
    longDescription: 'The 1000-seat AC auditorium features a professional-grade sound system, programmable stage lighting, a 20x30 ft LED screen, green room facilities, and a 50-seat VIP balcony.',
    image: 'https://images.unsplash.com/photo-1519167758481-83f550bb49b3?w=600&q=80',
    icon: <HiOutlineAcademicCap className="w-10 h-10" />,
    color: 'from-indigo-500 to-indigo-600',
    bgLight: 'bg-indigo-50',
    textColor: 'text-indigo-600',
    borderColor: 'border-indigo-200',
    capacity: '1000 seats',
    total: '20,000 sq ft',
    timing: '8:00 AM - 8:00 PM',
    incharge: 'Mr. Arvind Menon',
    phone: '+91 98765 43218',
    location: 'Cultural Center, Main Campus',
    features: ['LED Screen', 'Pro Sound System', 'Stage Lighting', 'Green Room', 'VIP Balcony'],
  },
  {
    id: 10,
    title: 'Music & Arts Studio',
    category: 'Cultural',
    description: 'Dedicated spaces for music, dance, and visual arts with soundproof rooms and professional-grade instruments.',
    longDescription: 'Our arts block houses a 40-seat music room with 20 keyboard stations, a soundproof drum room, a dance studio with mirrored walls and ballet barres, and a visual arts studio with pottery wheels, kilns, and ample natural lighting.',
    image: 'https://images.unsplash.com/photo-1514320291840-2e0a9bf2a9ae?w=600&q=80',
    icon: <HiOutlineMusicalNote className="w-10 h-10" />,
    color: 'from-violet-500 to-violet-600',
    bgLight: 'bg-violet-50',
    textColor: 'text-violet-600',
    borderColor: 'border-violet-200',
    capacity: '40 per session',
    total: '3 studios',
    timing: '8:00 AM - 5:00 PM',
    incharge: 'Ms. Ananya Gupta',
    phone: '+91 98765 43219',
    location: 'Cultural Center, Floor 2',
    features: ['Keyboard Lab', 'Dance Studio', 'Pottery Studio', 'Soundproof Rooms', 'Music Instruments'],
  },
  {
    id: 11,
    title: 'Hostel',
    category: 'Infrastructure',
    description: 'Separate boys and girls hostels with 24/7 security, WiFi, common rooms, and nutritious dining facilities.',
    longDescription: 'Our residential facilities include separate hostels for boys and girls with a combined capacity of 300 students. Rooms are spacious with attached bathrooms, study tables, and wardrobes. Facilities include 24/7 WiFi, RO water purifiers, common rooms with TV, indoor games, a reading room, and a dedicated mess.',
    image: 'https://images.unsplash.com/photo-1562774053-701939374585?w=600&q=80',
    icon: <HiOutlineBuildingOffice2 className="w-10 h-10" />,
    color: 'from-teal-500 to-teal-600',
    bgLight: 'bg-teal-50',
    textColor: 'text-teal-600',
    borderColor: 'border-teal-200',
    capacity: '300 students',
    total: '2 hostels',
    timing: '24/7',
    incharge: 'Mr. Ravi Shankar (Boys), Mrs. Sunita Devi (Girls)',
    phone: '+91 98765 43220',
    location: 'Hostel Complex, West Campus',
    features: ['24/7 Security', 'WiFi', 'Common Room', 'RO Water', 'Mess'],
  },
  {
    id: 12,
    title: 'Swimming Pool',
    category: 'Sports',
    description: 'A 25-meter semi-Olympic swimming pool with trained lifeguards, changing rooms, and regular swimming coaching.',
    longDescription: 'Our semi-Olympic 25m x 12.5m swimming pool has 6 lanes with anti-wave lane ropes, a deep end of 4.5ft to 12ft, and a separate kiddie pool. The pool is heated during winter months and has a state-of-the-art filtration system.',
    image: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=600&q=80',
    icon: <HiOutlineGlobeAlt className="w-10 h-10" />,
    color: 'from-sky-500 to-sky-600',
    bgLight: 'bg-sky-50',
    textColor: 'text-sky-600',
    borderColor: 'border-sky-200',
    capacity: '60 per session',
    total: '25m x 12.5m',
    timing: '6:30 AM - 5:30 PM',
    incharge: 'Coach Rajat Verma',
    phone: '+91 98765 43221',
    location: 'Sports Complex, East Campus',
    features: ['Heated Pool', 'Kiddie Pool', 'Lifeguards', 'Coaching', 'Filtration System'],
  },
];

export default facilitiesData;
